export const SOCKET_CONNECT_START = 'SOCKET_CONNECT_START';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_FAILURE = 'SOCKET_CONNECT_FAILURE';

export const SUBSCRIBE_START = 'SUBSCRIBE_START';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE';

export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE';

export const JOIN_ROOM_START = 'JOIN_ROOM_START';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_FAILURE = 'JOIN_ROOM_FAILURE';

export const UPDATE_USERS_START = 'UPDATE_USERS_START';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';

export const UPDATE_CHATLOG_START = 'UPDATE_CHATLOG_START';
export const UPDATE_CHATLOG_SUCCESS = 'UPDATE_CHATLOG_SUCCESS';
export const UPDATE_CHATLOG_FAILURE = 'UPDATE_CHATLOG_FAILURE';
